name: Readme Chess
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  issue_comment:
    types: [created]
jobs:
  update-chess:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/readme-chess@v1
        with:
          BOT: true 
          MOVE: ${{ github.event.comment.body }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALLOWED_USERS: GANGAR
