name: Readme Chess
on:
  workflow_dispatch:
  # This is the main trigger: a new comment on an issue
  issue_comment:
    types: [created]
jobs:
  update-chess:
    runs-on: ubuntu-latest
    permissions:
      # Required to update the README
      contents: write
      # Required to update the issue
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/readme-chess@v1
        with:
          BOT: true 
          MOVE: ${{ github.event.comment.body }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALLOWED_USERS: itsmeganga
