name: WakaTime Stats
on:
  schedule:
    # Runs at midnight every day
    - cron: "0 0 * * *"
  # Allows you to run this workflow manually
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      # This permission is required to update the README file
      contents: write
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # IMPORTANT: Make sure this is your WakaTime username
          USER_NAME: itsmeganga
